package es.jnsoft.whatweath.presentation.model

data class HourlyPresentation(
    val clouds: String,
    val deltaTime: Long,
    val description: String,
    val dewPoint: String,
    val humidity: String,
    val icon: String,
    val lat: Double,
    val lon: Double,
    val pop: Int,
    val pressure: Int,
    val rain: Double,
    val rainText: String,
    val snow: Double,
    val snowText: String,
    val temp: Int,
    val tempText: String,
    val tempFeelsLike: String,
    val timeText: String,
    val timeZone: Int,
    val uvi: Double,
    val visibility: String,
    val windDegrees: Int,
    val windDegreesText: String,
    val windSpeed: Double,
    val windSpeedText: String
) : BasePresentation
